on:
  push:
    branches:
    - main

env:
  IMAGE_TAG: "v1.0.0"
  IMAGE_NAME: "jenkins-build-agent-maven"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Docker build and push
      run: |

        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest -t ${{ env.DOCKERHUB_USERNAME }}/{{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest ${{ env.DOCKERHUB_USERNAME }}/{{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Logout Dockerhub
      run: |

        docker logout